-- EpisodeClient (LocalScript in StarterPlayer > StarterPlayerScripts)
-- Draws the episode: camera moves, speech bubbles, title cards, fades and the mural reveal.
-- Generated by roblox-channel/build.py.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local TweenService = game:GetService("TweenService")
local StarterGui = game:GetService("StarterGui")
local RunService = game:GetService("RunService")

local player = Players.LocalPlayer
local camera = workspace.CurrentCamera
local playerGui = player:WaitForChild("PlayerGui")

local FONT = Enum.Font.FredokaOne
local INK = Color3.fromRGB(40, 28, 70)
local NAME_COLORS = --[[NAME_COLORS]]

-- hide Roblox's own UI so the recording is clean
task.spawn(function()
	for _ = 1, 20 do
		pcall(function() StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.All, false) end)
		pcall(function() StarterGui:SetCore("TopbarEnabled", false) end)
		task.wait(0.5)
	end
end)

-- park our own avatar far away, out of shot
local function park(char)
	local root = char:WaitForChild("HumanoidRootPart")
	root.Anchored = true
	char:PivotTo(CFrame.new(0, 400, 600))
end
if player.Character then task.spawn(park, player.Character) end
player.CharacterAdded:Connect(park)

-- ---------- screen layers ----------
local screen = Instance.new("ScreenGui")
screen.Name = "Episode"
screen.IgnoreGuiInset = true
screen.ResetOnSpawn = false
screen.DisplayOrder = 10
screen.Parent = playerGui

local black = Instance.new("Frame")
black.Size = UDim2.fromScale(1, 1)
black.BackgroundColor3 = Color3.new(0, 0, 0)
black.BorderSizePixel = 0
black.ZIndex = 50
black.Parent = screen

local function corner(parent, r)
	local c = Instance.new("UICorner")
	c.CornerRadius = r
	c.Parent = parent
end
local function stroke(parent, color, thick)
	local s = Instance.new("UIStroke")
	s.Color = color
	s.Thickness = thick
	s.ApplyStrokeMode = Enum.ApplyStrokeMode.Border
	s.Parent = parent
	return s
end

-- ---------- camera ----------
local camTween
local function shot(pos, look, tweenTime)
	camera.CameraType = Enum.CameraType.Scriptable
	if camTween then camTween:Cancel() end
	local target = CFrame.lookAt(pos, look)
	if not tweenTime or tweenTime <= 0 then
		camera.CFrame = target
	else
		camTween = TweenService:Create(camera, TweenInfo.new(tweenTime, Enum.EasingStyle.Sine, Enum.EasingDirection.InOut), { CFrame = target })
		camTween:Play()
	end
end
-- the default camera script keeps trying to take over until we own it
RunService.RenderStepped:Connect(function()
	if camera.CameraType ~= Enum.CameraType.Scriptable then camera.CameraType = Enum.CameraType.Scriptable end
end)
camera.FieldOfView = 55

-- ---------- speech bubbles ----------
local bubble
local function say(name, text, duration)
	if bubble then bubble:Destroy() end
	local cast = workspace:FindFirstChild("Cast")
	local actor = cast and cast:FindFirstChild(name)
	local head = actor and actor:FindFirstChild("Head")
	if not head then return end
	local narration = string.sub(text, 1, 1) == "("

	local bb = Instance.new("BillboardGui")
	bb.Adornee = head
	bb.Size = UDim2.fromOffset(520, 150)
	bb.StudsOffset = Vector3.new(0, 3.1, 0)
	bb.AlwaysOnTop = true
	bb.MaxDistance = 1000
	bb.Parent = playerGui
	bubble = bb

	local holder = Instance.new("Frame")
	holder.AnchorPoint = Vector2.new(0.5, 1)
	holder.Position = UDim2.fromScale(0.5, 1)
	holder.Size = UDim2.fromScale(1, 1)
	holder.BackgroundTransparency = 1
	holder.Parent = bb
	local scale = Instance.new("UIScale")
	scale.Scale = 0.4
	scale.Parent = holder

	local box = Instance.new("Frame")
	box.Size = UDim2.new(1, 0, 1, -18)
	box.BackgroundColor3 = narration and Color3.fromRGB(245, 240, 255) or Color3.new(1, 1, 1)
	box.Parent = holder
	corner(box, UDim.new(0, 26))
	stroke(box, INK, 4)
	local tail = Instance.new("Frame")
	tail.AnchorPoint = Vector2.new(0.5, 0.5)
	tail.Position = UDim2.new(0.5, 0, 1, -20)
	tail.Size = UDim2.fromOffset(26, 26)
	tail.Rotation = 45
	tail.BackgroundColor3 = box.BackgroundColor3
	tail.ZIndex = 0
	tail.Parent = holder
	stroke(tail, INK, 4)

	local tag = Instance.new("TextLabel")
	tag.AnchorPoint = Vector2.new(0, 0.5)
	tag.Position = UDim2.fromOffset(22, 0)
	tag.Size = UDim2.fromOffset(170, 40)
	tag.AutomaticSize = Enum.AutomaticSize.X
	tag.BackgroundColor3 = NAME_COLORS[name] or INK
	tag.Text = "  " .. string.upper(name) .. "  "
	tag.Font = FONT
	tag.TextSize = 26
	tag.TextColor3 = Color3.new(1, 1, 1)
	tag.ZIndex = 3
	tag.Parent = box
	corner(tag, UDim.new(1, 0))

	local label = Instance.new("TextLabel")
	label.Position = UDim2.fromOffset(24, 24)
	label.Size = UDim2.new(1, -48, 1, -36)
	label.BackgroundTransparency = 1
	label.Text = text
	label.Font = FONT
	label.TextScaled = true
	label.TextWrapped = true
	label.TextColor3 = narration and Color3.fromRGB(110, 90, 150) or INK
	label.MaxVisibleGraphemes = 0
	label.ZIndex = 3
	label.Parent = box
	local limit = Instance.new("UITextSizeConstraint")
	limit.MaxTextSize = 40
	limit.Parent = label

	TweenService:Create(scale, TweenInfo.new(0.28, Enum.EasingStyle.Back, Enum.EasingDirection.Out), { Scale = 1 }):Play()
	-- typewriter
	task.spawn(function()
		local n = utf8.len(text) or #text
		local typeTime = math.min(duration * 0.45, n * 0.03)
		local t0 = os.clock()
		while label.Parent and label.MaxVisibleGraphemes < n do
			label.MaxVisibleGraphemes = math.floor((os.clock() - t0) / typeTime * n)
			task.wait()
		end
		if label.Parent then label.MaxVisibleGraphemes = -1 end
	end)
	task.delay(math.max(0.3, duration - 0.25), function()
		if bb.Parent then
			TweenService:Create(scale, TweenInfo.new(0.18), { Scale = 0.6 }):Play()
			task.wait(0.18)
			bb:Destroy()
		end
	end)
end

-- ---------- announcements (top banner) ----------
local function announce(who, text, duration)
	local f = Instance.new("Frame")
	f.AnchorPoint = Vector2.new(0.5, 0)
	f.Position = UDim2.new(0.5, 0, 0, -160)
	f.Size = UDim2.new(0.7, 0, 0, 140)
	f.BackgroundColor3 = Color3.fromRGB(40, 60, 110)
	f.Parent = screen
	corner(f, UDim.new(0, 24))
	stroke(f, Color3.fromRGB(255, 230, 120), 5)
	local h = Instance.new("TextLabel")
	h.Size = UDim2.new(1, 0, 0, 44)
	h.Position = UDim2.fromOffset(0, 10)
	h.BackgroundTransparency = 1
	h.Text = who
	h.Font = FONT
	h.TextSize = 34
	h.TextColor3 = Color3.fromRGB(255, 230, 120)
	h.Parent = f
	local t = Instance.new("TextLabel")
	t.Size = UDim2.new(1, -40, 1, -64)
	t.Position = UDim2.fromOffset(20, 56)
	t.BackgroundTransparency = 1
	t.Text = text
	t.Font = FONT
	t.TextScaled = true
	t.TextWrapped = true
	t.TextColor3 = Color3.new(1, 1, 1)
	t.Parent = f
	local lim = Instance.new("UITextSizeConstraint")
	lim.MaxTextSize = 36
	lim.Parent = t
	TweenService:Create(f, TweenInfo.new(0.4, Enum.EasingStyle.Back), { Position = UDim2.new(0.5, 0, 0, 40) }):Play()
	task.delay(duration - 0.4, function()
		TweenService:Create(f, TweenInfo.new(0.35), { Position = UDim2.new(0.5, 0, 0, -170) }):Play()
		task.wait(0.4)
		f:Destroy()
	end)
end

-- ---------- full-screen cards ----------
local function card(text, sub, duration)
	local f = Instance.new("Frame")
	f.Size = UDim2.fromScale(1, 1)
	f.BackgroundColor3 = Color3.fromRGB(28, 22, 52)
	f.ZIndex = 60
	f.Parent = screen
	local grad = Instance.new("UIGradient")
	grad.Color = ColorSequence.new(Color3.fromRGB(70, 40, 120), Color3.fromRGB(20, 18, 46))
	grad.Rotation = 90
	grad.Parent = f
	local t = Instance.new("TextLabel")
	t.AnchorPoint = Vector2.new(0.5, 0.5)
	t.Position = UDim2.fromScale(0.5, sub ~= "" and 0.44 or 0.5)
	t.Size = UDim2.fromScale(0.8, 0.18)
	t.BackgroundTransparency = 1
	t.Text = text
	t.Font = FONT
	t.TextScaled = true
	t.TextColor3 = Color3.fromRGB(255, 230, 120)
	t.ZIndex = 61
	t.Parent = f
	local ts = Instance.new("UIStroke")
	ts.Thickness = 4
	ts.Color = INK
	ts.Parent = t
	if sub ~= "" then
		local s = Instance.new("TextLabel")
		s.AnchorPoint = Vector2.new(0.5, 0.5)
		s.Position = UDim2.fromScale(0.5, 0.6)
		s.Size = UDim2.fromScale(0.7, 0.08)
		s.BackgroundTransparency = 1
		s.Text = sub
		s.Font = FONT
		s.TextScaled = true
		s.TextColor3 = Color3.new(1, 1, 1)
		s.ZIndex = 61
		s.Parent = f
	end
	local sc = Instance.new("UIScale")
	sc.Scale = 0.85
	sc.Parent = t
	TweenService:Create(sc, TweenInfo.new(0.5, Enum.EasingStyle.Back), { Scale = 1 }):Play()
	task.delay(duration, function() f:Destroy() end)
end

local function fade(direction, duration)
	local target = direction == "out" and 0 or 1
	TweenService:Create(black, TweenInfo.new(duration), { BackgroundTransparency = target }):Play()
end

local function revealMural()
	local wall = workspace:FindFirstChild("Set") and workspace.Set:FindFirstChild("MuralWall")
	if not wall then return end
	local items = {}
	for _, d in ipairs(wall:GetDescendants()) do
		if d:GetAttribute("Reveal") then table.insert(items, d) end
	end
	for i, d in ipairs(items) do
		local info = TweenInfo.new(0.7, Enum.EasingStyle.Quad, Enum.EasingDirection.Out, 0, false, (i - 1) * 0.12)
		if d:IsA("TextLabel") then
			TweenService:Create(d, info, { TextTransparency = 0 }):Play()
			local s = d:FindFirstChildOfClass("UIStroke")
			if s then TweenService:Create(s, info, { Transparency = 0 }):Play() end
		else
			TweenService:Create(d, info, { BackgroundTransparency = 0 }):Play()
		end
	end
end

-- ---------- cues from the server ----------
local remote = ReplicatedStorage:WaitForChild("Director")
remote.OnClientEvent:Connect(function(kind, a, b, c, d)
	if kind == "shot" then
		shot(a, b, c)
	elseif kind == "say" then
		say(a, b, c)
	elseif kind == "announce" then
		announce(a, b, c)
	elseif kind == "card" then
		card(a, b, c)
	elseif kind == "fade" then
		fade(a, b)
	elseif kind == "mural" then
		revealMural()
	elseif kind == "end" then
		fade("out", 1)
	end
end)
