-- EpisodeServer (Script in ServerScriptService)
-- Builds the set and the cast, then plays the episode timeline.
-- The camera, speech bubbles and title cards are drawn by EpisodeClient.
-- Generated by roblox-channel/build.py: edit the episode file, not this script.

local Players = game:GetService("Players")
local ReplicatedStorage = game:GetService("ReplicatedStorage")
local Lighting = game:GetService("Lighting")

local EPISODE = "--[[EPISODE_TITLE]]"

local remote = Instance.new("RemoteEvent")
remote.Name = "Director"
remote.Parent = ReplicatedStorage

for _, name in ipairs({ "Baseplate", "SpawnLocation" }) do
	local p = workspace:FindFirstChild(name)
	if p then p:Destroy() end
end

local setFolder = Instance.new("Folder")
setFolder.Name = "Set"
setFolder.Parent = workspace
local castFolder = Instance.new("Folder")
castFolder.Name = "Cast"
castFolder.Parent = workspace

local function rgb(t) return Color3.fromRGB(t[1], t[2], t[3]) end

-- ---------- building helpers ----------
local function part(size, cframe, color, material, parent)
	local p = Instance.new("Part")
	p.Anchored = true
	p.Size = size
	p.CFrame = cframe
	p.Color = color
	p.Material = material or Enum.Material.SmoothPlastic
	p.TopSurface = Enum.SurfaceType.Smooth
	p.BottomSurface = Enum.SurfaceType.Smooth
	p.Parent = parent or setFolder
	return p
end

local function ball(size, cframe, color, parent)
	local p = part(size, cframe, color, Enum.Material.SmoothPlastic, parent)
	local m = Instance.new("SpecialMesh")
	m.MeshType = Enum.MeshType.Sphere
	m.Parent = p
	return p
end

local function frame(parent, props)
	local f = Instance.new(props.Class or "Frame")
	for k, v in pairs(props) do
		if k ~= "Class" and k ~= "Corner" and k ~= "Gradient" and k ~= "Stroke" then f[k] = v end
	end
	if props.Corner then
		local c = Instance.new("UICorner")
		c.CornerRadius = props.Corner
		c.Parent = f
	end
	if props.Gradient then
		local g = Instance.new("UIGradient")
		g.Color = props.Gradient
		g.Rotation = 90
		g.Parent = f
	end
	if props.Stroke then
		local s = Instance.new("UIStroke")
		s.Color = props.Stroke
		s.Thickness = 6
		s.Parent = f
	end
	f.Parent = parent
	return f
end

local function tree(x, z, s)
	part(Vector3.new(1.6 * s, 7 * s, 1.6 * s), CFrame.new(x, 0.5 + 3.5 * s, z), Color3.fromRGB(110, 72, 44), Enum.Material.Wood)
	ball(Vector3.new(9 * s, 8 * s, 9 * s), CFrame.new(x, 0.5 + 9 * s, z), Color3.fromRGB(86, 160, 72))
	ball(Vector3.new(6 * s, 5 * s, 6 * s), CFrame.new(x + 2 * s, 0.5 + 12 * s, z - 1 * s), Color3.fromRGB(104, 178, 84))
end

local function picnicTable(name, x, z, color, seats)
	local wood = rgb(color)
	part(Vector3.new(10, 0.6, 4), CFrame.new(x, 3.3, z), wood, Enum.Material.Wood)
	for _, dx in ipairs({ -4, 4 }) do
		part(Vector3.new(0.6, 3, 3), CFrame.new(x + dx, 1.8, z), wood:Lerp(Color3.new(0, 0, 0), 0.2), Enum.Material.Wood)
	end
	for _, dz in ipairs({ -3.6, 3.6 }) do
		part(Vector3.new(10, 0.5, 1.6), CFrame.new(x, 1.7, z + dz), wood, Enum.Material.Wood)
		part(Vector3.new(0.5, 1.2, 1.2), CFrame.new(x - 4, 0.9, z + dz), wood, Enum.Material.Wood)
		part(Vector3.new(0.5, 1.2, 1.2), CFrame.new(x + 4, 0.9, z + dz), wood, Enum.Material.Wood)
	end
	for seatName, s in pairs(seats or {}) do
		local seat = Instance.new("Seat")
		seat.Name = seatName
		seat.Anchored = true
		seat.Size = Vector3.new(2, 0.3, 1.4)
		seat.CFrame = CFrame.new(s[1], 2.05, s[2]) * CFrame.Angles(0, s[3], 0)
		seat.Transparency = 1
		seat.CanCollide = false
		seat.Parent = setFolder
	end
end

-- ---------- the set: Maple Lane Middle School courtyard ----------
local function buildSet()
	Lighting.ClockTime = 14.5
	Lighting.Brightness = 2.4
	Lighting.OutdoorAmbient = Color3.fromRGB(150, 150, 165)
	local atmo = Instance.new("Atmosphere")
	atmo.Density = 0.28
	atmo.Haze = 1.2
	atmo.Color = Color3.fromRGB(205, 225, 255)
	atmo.Parent = Lighting
	local cc = Instance.new("ColorCorrectionEffect")
	cc.Saturation = 0.12
	cc.Contrast = 0.05
	cc.Parent = Lighting
	local bloom = Instance.new("BloomEffect")
	bloom.Intensity = 0.4
	bloom.Threshold = 1.6
	bloom.Parent = Lighting

	part(Vector3.new(400, 1, 400), CFrame.new(0, 0, 0), Color3.fromRGB(92, 164, 76), Enum.Material.Grass)
	part(Vector3.new(84, 0.2, 66), CFrame.new(0, 0.6, -2), Color3.fromRGB(196, 190, 182), Enum.Material.Concrete)

	-- school building
	local wall = Color3.fromRGB(226, 196, 156)
	part(Vector3.new(110, 30, 10), CFrame.new(0, 15.5, -35), wall, Enum.Material.Brick)
	part(Vector3.new(112, 1.4, 12), CFrame.new(0, 31, -35), Color3.fromRGB(150, 70, 60))
	for _, x in ipairs({ -48, -40, -32, -24, 24, 32, 40, 48, -36, 36 }) do
		part(Vector3.new(5, 5, 0.4), CFrame.new(x, 8, -29.9), Color3.fromRGB(150, 200, 235), Enum.Material.Glass)
	end
	for x = -48, 48, 8 do
		part(Vector3.new(5, 5, 0.4), CFrame.new(x, 24, -29.9), Color3.fromRGB(150, 200, 235), Enum.Material.Glass)
	end
	part(Vector3.new(7, 10, 0.5), CFrame.new(27.5, 5.5, -29.85), Color3.fromRGB(90, 60, 50), Enum.Material.Wood)

	local sign = part(Vector3.new(40, 3.2, 0.5), CFrame.new(0, 19.6, -29.8), Color3.fromRGB(40, 60, 110))
	local sg = Instance.new("SurfaceGui")
	sg.Face = Enum.NormalId.Back
	sg.Parent = sign
	frame(sg, { Class = "TextLabel", Size = UDim2.fromScale(1, 1), BackgroundTransparency = 1,
		Text = "MAPLE LANE MIDDLE SCHOOL", TextScaled = true, Font = Enum.Font.FredokaOne,
		TextColor3 = Color3.fromRGB(255, 230, 120) })

	-- the blank wall that becomes Mia's mural
	local muralWall = part(Vector3.new(34, 14, 0.8), CFrame.new(0, 10, -29.3), Color3.fromRGB(245, 243, 238))
	muralWall.Name = "MuralWall"
	local mg = Instance.new("SurfaceGui")
	mg.Name = "Mural"
	mg.Face = Enum.NormalId.Back
	mg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	mg.PixelsPerStud = 40
	mg.Parent = muralWall
	-- every mural piece starts invisible; EpisodeClient fades them in on the "mural" cue
	local function m(props)
		props.BackgroundTransparency = 1
		local f = frame(mg, props)
		f:SetAttribute("Reveal", true)
		local stroke = f:FindFirstChildOfClass("UIStroke")
		if stroke then stroke.Transparency = 1 end
		return f
	end
	m({ Size = UDim2.fromScale(1, 1), BackgroundColor3 = Color3.new(1, 1, 1),
		Gradient = ColorSequence.new(Color3.fromRGB(120, 200, 255), Color3.fromRGB(255, 190, 220)) })
	m({ Size = UDim2.fromScale(0.16, 0.36), Position = UDim2.fromScale(0.76, 0.08),
		BackgroundColor3 = Color3.fromRGB(255, 214, 70), Corner = UDim.new(1, 0) })
	local arcColors = { { 255, 90, 90 }, { 255, 160, 60 }, { 255, 225, 80 }, { 90, 200, 120 }, { 80, 150, 255 }, { 160, 100, 230 } }
	for i, c in ipairs(arcColors) do
		local s = 0.9 - (i - 1) * 0.08
		m({ Size = UDim2.fromScale(s * 0.6, s * 1.25), Position = UDim2.fromScale(0.08 + (0.9 - s) * 0.3, 0.32 + (0.9 - s) * 0.6),
			BackgroundColor3 = rgb(c), Corner = UDim.new(1, 0) })
	end
	m({ Size = UDim2.fromScale(1, 0.32), Position = UDim2.fromScale(0, 0.68), BackgroundColor3 = Color3.fromRGB(110, 190, 90) })
	local kids = { { 255, 120, 170 }, { 80, 160, 255 }, { 190, 160, 240 }, { 255, 150, 70 }, { 120, 210, 140 } }
	for i, c in ipairs(kids) do
		local x = 0.12 + (i - 1) * 0.17
		m({ Size = UDim2.fromScale(0.06, 0.12), Position = UDim2.fromScale(x + 0.015, 0.5), BackgroundColor3 = Color3.fromRGB(150, 100, 70), Corner = UDim.new(1, 0) })
		m({ Size = UDim2.fromScale(0.09, 0.2), Position = UDim2.fromScale(x, 0.62), BackgroundColor3 = rgb(c), Corner = UDim.new(0.3, 0) })
	end
	m({ Class = "TextLabel", Size = UDim2.fromScale(0.7, 0.16), Position = UDim2.fromScale(0.15, 0.04), Text = "TOGETHER WE SHINE",
		TextScaled = true, Font = Enum.Font.FredokaOne, TextColor3 = Color3.new(1, 1, 1), TextTransparency = 1, Stroke = Color3.fromRGB(80, 40, 120) })

	picnicTable("TableA", -14, -2, { 170, 110, 70 }, nil)
	picnicTable("TableB", 16, 6, { 170, 110, 70 }, {
		SeatMia = { 16, 2.4, math.pi },
		SeatJay = { 16, 9.6, 0 },
	})
	-- Mia's sketchbook (hidden until she sits down)
	local book = part(Vector3.new(2.4, 0.12, 1.7), CFrame.new(16, 3.66, 4.5), Color3.fromRGB(255, 255, 255))
	book.Name = "Sketchbook"
	book.Transparency = 1
	local bg = Instance.new("SurfaceGui")
	bg.Face = Enum.NormalId.Top
	bg.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	bg.PixelsPerStud = 120
	bg.Enabled = false
	bg.Parent = book
	frame(bg, { Size = UDim2.fromScale(1, 1), BackgroundColor3 = Color3.fromRGB(250, 248, 240) })
	frame(bg, { Size = UDim2.fromScale(0.9, 0.5), Position = UDim2.fromScale(0.05, 0.05), BackgroundColor3 = Color3.fromRGB(150, 205, 255) })
	frame(bg, { Size = UDim2.fromScale(0.9, 0.38), Position = UDim2.fromScale(0.05, 0.55), BackgroundColor3 = Color3.fromRGB(120, 195, 100) })
	frame(bg, { Size = UDim2.fromScale(0.5, 0.32), Position = UDim2.fromScale(0.25, 0.25), BackgroundColor3 = Color3.fromRGB(226, 196, 156) })
	frame(bg, { Size = UDim2.fromScale(0.16, 0.22), Position = UDim2.fromScale(0.75, 0.1), BackgroundColor3 = Color3.fromRGB(255, 214, 70), Corner = UDim.new(1, 0) })
	frame(bg, { Size = UDim2.fromScale(0.05, 0.2), Position = UDim2.fromScale(0.12, 0.45), BackgroundColor3 = Color3.fromRGB(110, 72, 44) })
	frame(bg, { Size = UDim2.fromScale(0.18, 0.24), Position = UDim2.fromScale(0.055, 0.26), BackgroundColor3 = Color3.fromRGB(86, 160, 72), Corner = UDim.new(1, 0) })

	tree(-38, -8, 1)
	tree(39, -16, 1.1)
	tree(-34, 24, 0.9)
	tree(36, 28, 1)
	tree(-48, 10, 1.2)
end

-- ---------- the cast ----------
local ANIMS = {
	idle = "507766666", walk = "507777826", wave = "507770239", point = "507770453",
	cheer = "507770677", laugh = "507770818", dance = "507771019", sit = "2506281703",
}

local cast = {}

local function hairPiece(model, size, offset, color)
	local head = model:FindFirstChild("Head")
	local p = Instance.new("Part")
	p.Size = size
	p.Color = color
	p.Material = Enum.Material.SmoothPlastic
	p.CanCollide = false
	p.CanQuery = false
	p.Massless = true
	p.CFrame = head.CFrame * offset
	local mesh = Instance.new("SpecialMesh")
	mesh.MeshType = Enum.MeshType.Sphere
	mesh.Parent = p
	local w = Instance.new("WeldConstraint")
	w.Part0 = head
	w.Part1 = p
	w.Parent = p
	p.Parent = model
end

-- simple part-built hairstyles, so no catalog items are needed
local function addHair(model, style, color)
	local c = rgb(color)
	if style == "bald" then return end
	hairPiece(model, Vector3.new(1.34, 0.9, 1.3), CFrame.new(0, 0.42, 0.2), c)
	if style == "puffs" then
		hairPiece(model, Vector3.new(0.95, 0.95, 0.95), CFrame.new(-0.62, 0.62, 0.2), c)
		hairPiece(model, Vector3.new(0.95, 0.95, 0.95), CFrame.new(0.62, 0.62, 0.2), c)
	elseif style == "ponytail" then
		hairPiece(model, Vector3.new(0.6, 0.6, 0.6), CFrame.new(0, 0.45, 0.75), c)
		hairPiece(model, Vector3.new(0.5, 1.1, 0.5), CFrame.new(0, -0.1, 0.9), c)
	elseif style == "spiky" then
		for i = -1, 1 do
			hairPiece(model, Vector3.new(0.45, 0.8, 0.45), CFrame.new(i * 0.38, 0.85, 0.05) * CFrame.Angles(0, 0, -i * 0.4), c)
		end
	elseif style == "long" then
		hairPiece(model, Vector3.new(1.4, 1.6, 0.6), CFrame.new(0, -0.15, 0.55), c)
	elseif style == "short" then
		hairPiece(model, Vector3.new(1.3, 0.5, 1.2), CFrame.new(0, 0.6, 0.12), c)
	end
end

local function track(actor, name)
	if not actor.tracks[name] then
		local a = Instance.new("Animation")
		a.AnimationId = "rbxassetid://" .. ANIMS[name]
		actor.tracks[name] = actor.animator:LoadAnimation(a)
	end
	return actor.tracks[name]
end

local function stopAll(actor, except)
	for name, t in pairs(actor.tracks) do
		if name ~= except then t:Stop(0.25) end
	end
end

local function makeActor(def)
	local hd = Instance.new("HumanoidDescription")
	local skin, shirt, pants = rgb(def.skin), rgb(def.shirt), rgb(def.pants)
	hd.HeadColor = skin
	hd.TorsoColor = shirt
	hd.LeftArmColor = def.sleeves and shirt or skin
	hd.RightArmColor = def.sleeves and shirt or skin
	hd.LeftLegColor = pants
	hd.RightLegColor = pants
	local model = Players:CreateHumanoidModelFromDescription(hd, Enum.HumanoidRigType.R15)
	model.Name = def.name
	local animate = model:FindFirstChild("Animate")
	if animate then animate:Destroy() end
	model:PivotTo(CFrame.new(def.x, 3.6, def.z) * CFrame.Angles(0, def.yaw or 0, 0))
	model.Parent = castFolder
	addHair(model, def.hair, def.hairColor)
	local humanoid = model:FindFirstChildOfClass("Humanoid")
	humanoid.DisplayDistanceType = Enum.HumanoidDisplayDistanceType.None
	local animator = humanoid:FindFirstChildOfClass("Animator")
	if not animator then
		animator = Instance.new("Animator")
		animator.Parent = humanoid
	end
	local root = model:WaitForChild("HumanoidRootPart")
	pcall(function() root:SetNetworkOwner(nil) end)
	local actor = { model = model, humanoid = humanoid, animator = animator, root = root, tracks = {} }
	cast[def.name] = actor
	local idle = track(actor, "idle")
	idle.Looped = true
	idle:Play()
	return actor
end

-- ---------- actions ----------
local function face(actor, x, z)
	local p = actor.root.Position
	actor.root.CFrame = CFrame.lookAt(p, Vector3.new(x, p.Y, z))
end

local function walkPath(actor, points, duration)
	task.spawn(function()
		local total, prev = 0, actor.root.Position
		for _, pt in ipairs(points) do
			local v = Vector3.new(pt[1], prev.Y, pt[2])
			total = total + (v - prev).Magnitude
			prev = v
		end
		local speed = math.max(2, total / duration)
		actor.humanoid.WalkSpeed = speed
		local w = track(actor, "walk")
		w.Looped = true
		w:Play(0.2)
		w:AdjustSpeed(math.clamp(speed / 10, 0.6, 1.4))
		for _, pt in ipairs(points) do
			actor.humanoid:MoveTo(Vector3.new(pt[1], actor.root.Position.Y, pt[2]))
			actor.humanoid.MoveToFinished:Wait()
		end
		w:Stop(0.3)
	end)
end

local function sit(actor, seatName)
	local seat = setFolder:FindFirstChild(seatName)
	seat:Sit(actor.humanoid)
	stopAll(actor, "idle")
	local s = track(actor, "sit")
	s.Looped = true
	s:Play(0.2)
end

local function place(actor, x, z, yaw)
	actor.humanoid.Sit = false
	for _, d in ipairs(actor.model:GetDescendants()) do
		if d:IsA("Weld") and d.Name == "SeatWeld" then d:Destroy() end
	end
	for _, seat in ipairs(setFolder:GetChildren()) do
		if seat:IsA("Seat") and seat.Occupant == actor.humanoid then
			local w = seat:FindFirstChild("SeatWeld")
			if w then w:Destroy() end
		end
	end
	stopAll(actor, "idle")
	task.wait()
	actor.model:PivotTo(CFrame.new(x, 3.6, z) * CFrame.Angles(0, yaw or 0, 0))
end

local function anim(actor, name, looped)
	stopAll(actor, "idle")
	local t = track(actor, name)
	t.Looped = looped and true or false
	t:Play(0.2)
end

-- ---------- run ----------
local CAST = --[[CAST]]
local STEPS = --[[STEPS]]

buildSet()
for _, def in ipairs(CAST) do makeActor(def) end

if #Players:GetPlayers() == 0 then Players.PlayerAdded:Wait() end
task.wait(5) -- let the client load; the screen stays black meanwhile
print("[" .. EPISODE .. "] action!")

for i, s in ipairs(STEPS) do
	local kind = s[1]
	if kind == "shot" or kind == "say" or kind == "card" or kind == "announce" or kind == "fade" or kind == "mural" or kind == "end" then
		remote:FireAllClients(kind, s[2], s[3], s[4], s[5])
	elseif kind == "walk" then
		walkPath(cast[s[2]], s[3], s[4])
	elseif kind == "face" then
		face(cast[s[2]], s[3], s[4])
	elseif kind == "sit" then
		sit(cast[s[2]], s[3])
	elseif kind == "place" then
		place(cast[s[2]], s[3], s[4], s[5])
	elseif kind == "anim" then
		anim(cast[s[2]], s[3], s[4])
	elseif kind == "stop" then
		stopAll(cast[s[2]], "idle")
	elseif kind == "prop" then
		local p = setFolder:FindFirstChild(s[2])
		p.Transparency = s[3] and 0 or 1
		local g = p:FindFirstChildOfClass("SurfaceGui")
		if g then g.Enabled = s[3] end
	end
	-- steps that take screen time block the timeline
	if kind == "say" or kind == "card" or kind == "announce" then
		task.wait(s[4])
	elseif kind == "fade" then
		task.wait(s[3])
	elseif kind == "wait" then
		task.wait(s[2])
	end
end
print("[" .. EPISODE .. "] cut! That's a wrap.")
